# Generated by Django 2.2 on 2021-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('upd_date', models.DateTimeField()),
                ('poll_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
