# Generated by Django 2.2 on 2021-01-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_testwork_app', '0002_answer_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
    ]
